version: "3"

services:
  web:
    build:
      context: .
      args:
        nodeEvn: development
    command: npm run dev
    volumes:
      - ./dist:/app/dist
    ports:
      - "8080:8080"
      - "9229:9229"